version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - /data/postgres:/data/postgres
    env_file:
    - docker.env
    networks:
    - postgres
 
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres

  backend-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: rafaelnwitter/backend-api:latest
    ports:
      - "3000:3000"
    container_name: backend-api
    depends_on: 
      - postgres
    volumes: 
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    networks: 
      - postgres
 
networks:
  postgres:
    driver: bridge